name: Docker Image CI

on:
  push:
    tags: [ "v*" ]

env:
  NODE_VERSION: '24.12.0'

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: "latest"
    - name: Environment Information
      run: npx envinfo
    - name: Get version number
      run: |
        $tagName = "${{ github.ref }}".Split("/")[2]
        $tagName = "${{ github.ref }}".Split("/")[2]
        Write-Host $tagName
        $upstreamTagName = $tagName.Split("-")[0]
        Write-Host $upstreamTagName
        Write-Output "TAG_NAME=$tagName" | Out-File -Append -Encoding ascii $env:GITHUB_ENV
        Write-Output "UPSTREAM_TAG_NAME=$upstreamTagName" | Out-File -Append -Encoding ascii $env:GITHUB_ENV
    - name: Checkout upstream
      run: git clone --depth 1 -b ${Env:UPSTREAM_TAG_NAME} https://github.com/devcontainers/cli.git upstream
    - name: Apply upstream patch
      run: git -C upstream apply ../upstream-bun.patch
    - name: Build
      run: .\build_windows_by_bun.ps1 ${Env:TAG_NAME}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: devcontainer-windows
        path: ./dist/devcontainer-windows-x64-${{ env.TAG_NAME }}.exe

  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: "latest"
    - name: Get version number
      run: |
        TAG_NAME=$(echo "${{ github.ref }}" | cut -d '/' -f 3)
        echo $TAG_NAME
        UPSTREAM_TAG_NAME=$(echo ${TAG_NAME} | cut -d '-' -f 1)
        echo $UPSTREAM_TAG_NAME
        echo "TAG_NAME=${TAG_NAME}" >> ${GITHUB_ENV}
        echo "UPSTREAM_TAG_NAME=${UPSTREAM_TAG_NAME}" >> ${GITHUB_ENV}
    - name: Checkout upstream
      run: git clone --depth 1 -b ${UPSTREAM_TAG_NAME} https://github.com/devcontainers/cli.git upstream
    - name: Apply upstream patch
      run: git -C upstream apply ../upstream-bun.patch
    - name: Build
      run: bash ./build_linux_by_bun.bash ${TAG_NAME}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: devcontainer-linux
        path: ./dist/devcontainer-linux-x64-${{ env.TAG_NAME }}

  build-darwin:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: "latest"
    - name: Get version number
      run: |
        TAG_NAME=$(echo "${{ github.ref }}" | cut -d '/' -f 3)
        echo $TAG_NAME
        UPSTREAM_TAG_NAME=$(echo ${TAG_NAME} | cut -d '-' -f 1)
        echo $UPSTREAM_TAG_NAME
        echo "TAG_NAME=${TAG_NAME}" >> ${GITHUB_ENV}
        echo "UPSTREAM_TAG_NAME=${UPSTREAM_TAG_NAME}" >> ${GITHUB_ENV}
    - name: Checkout upstream
      run: git clone --depth 1 -b ${UPSTREAM_TAG_NAME} https://github.com/devcontainers/cli.git upstream
    - name: Apply upstream patch
      run: git -C upstream apply ../upstream-bun.patch
    - name: Build
      run: bash ./build_darwin_by_bun.bash ${TAG_NAME}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: devcontainer-darwin
        path: ./dist/devcontainer-darwin-x64-${{ env.TAG_NAME }}

  release:
    needs: [build-linux, build-windows, build-darwin]
    runs-on: ubuntu-latest
    steps:
    - name: Download windows artifact
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: devcontainer-*
        merge-multiple: true
    - uses: ncipollo/release-action@v1
      with:
        artifacts: dist/*
        allowUpdates: true
        draft: true
